---
features:
  - org.ulagbulag.io/cni

cluster:
  name: twinx
  group: main
  singleNode: false
  standalone: false
  apiEndpoint: https://192.0.2.13:6443
  domainBase: openark
  nameservers:
    loadBalancer:
      ipv4: ""
  pods:
    ipv4:
      subnet: 10.124.0.0/16
      childSubnet: 10.124.0.0/16
      prefix: 24
  services:
    ipv4:
      subnet: 10.125.0.0/16
      childSubnet: 10.125.0.0/16
    kubeProxy:
      enabled: false

clusterRepository:
  name: twinx-sandbox-k8s
  revision: main

repo:
  baseUrl: https://github.com
  owner: SmartX-Team
  name: smartx-k8s
  revision: scalex-sandbox-smartx-k8s

tower:
  cluster: towerx
  controlPlane: false
  domainName: sandbox.invalid
  group: ops
