portal:
  deploymentName: isaac-portal
  namespace: omniverse
  image: 10.34.25.18/omniverse/isaac-twinx:0.2.2
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: harbor-regcred
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: 5196561c-de8e-e711-ab21-a4bf01269009
  service:
    type: LoadBalancer
    loadBalancerIP: 10.33.143.11
  writeEnabled: true
  isaacSimImage: 10.34.25.18/omniverse/isaac-sim:6.0
  isaacSimArm64Image: 10.34.25.18/omniverse/isaac-sim:6.0.1-arm64
  isaacSimStartXvfb: true
  isaacSimArm64StartXvfb: false
  isaacSimArm64HostNetwork: true
  instanceImagePullSecrets: harbor-regcred
  dra:
    apiVersion: resource.k8s.io/v1
    driver: gpu.nvidia.com
    deviceClass: gpu.nvidia.com
    migDeviceClass: mig.nvidia.com
  nucleus:
    server: omniverse://10.33.143.10/
    projectPath: Projects/demonstration
    secretName: nucleus-cred
    userKey: OMNI_USER
    passwordKey: OMNI_PASS
  streamInitializationSeconds: 120
  probes:
    readinessTimeoutSeconds: 5
    livenessTimeoutSeconds: 5
    livenessFailureThreshold: 6
