---
namespaces:
  - name: scalex-rgw-analysis-web
    owner: c-k8s
    labels:
      app.kubernetes.io/part-of: scalex-federation-poc
      scalex.io/release: rgw-analysis-web
  - name: scalex-temp-poc
    owner: c-k8s
    labels:
      app.kubernetes.io/part-of: scalex-federation-poc
      scalex.io/release: temp-poc
